"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { 
  Briefcase, 
  Building, 
  MapPin, 
  CheckCircle, 
  Plus, 
  X, 
  ArrowRight, 
  ArrowLeft,
  Sparkles,
  Loader2
} from "lucide-react"

interface ProspectAttributes {
  industries: string[]
  jobTitles: string[]
  companySizes: string[]
  locations: string[]
}

// AI-generated mock attributes based on product
const generateMockAttributes = (productName: string, description: string): ProspectAttributes => {
  // This would be generated by AI in production
  return {
    industries: [
      "Enterprise Software",
      "B2B SaaS",
      "Technology",
      "Financial Services",
      "Healthcare Technology"
    ],
    jobTitles: [
      "VP of Sales",
      "Sales Director",
      "Chief Revenue Officer",
      "Head of Business Development",
      "Director of Enterprise Accounts"
    ],
    companySizes: [
      "51-200 employees",
      "201-500 employees",
      "501-1000 employees",
      "1000+ employees"
    ],
    locations: [
      "United States",
      "United Kingdom",
      "Germany",
      "Canada",
      "Australia"
    ]
  }
}

export default function ProspectAttributesPage() {
  const router = useRouter()
  const [attributes, setAttributes] = useState<ProspectAttributes | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)

  // Industry input
  const [newIndustry, setNewIndustry] = useState("")
  const [newJobTitle, setNewJobTitle] = useState("")
  const [newCompanySize, setNewCompanySize] = useState("")
  const [newLocation, setNewLocation] = useState("")

  useEffect(() => {
    // Load from localStorage or generate new
    const storedSetup = localStorage.getItem("productSetup")
    const storedAttributes = localStorage.getItem("prospectAttributes")

    if (storedAttributes) {
      setAttributes(JSON.parse(storedAttributes))
    } else if (storedSetup) {
      const setup = JSON.parse(storedSetup)
      // Generate mock attributes based on product
      const generated = generateMockAttributes(setup.name, setup.description)
      setAttributes(generated)
    } else {
      // Default attributes if no setup
      setAttributes({
        industries: ["Technology", "Finance", "Healthcare"],
        jobTitles: ["CEO", "CTO", "VP Sales"],
        companySizes: ["10-50", "51-200", "201-500"],
        locations: ["United States", "United Kingdom"]
      })
    }
    setLoading(false)
  }, [])

  const handleAddIndustry = () => {
    if (!newIndustry.trim() || !attributes) return
    setAttributes({
      ...attributes,
      industries: [...attributes.industries, newIndustry.trim()]
    })
    setNewIndustry("")
  }

  const handleRemoveIndustry = (index: number) => {
    if (!attributes) return
    setAttributes({
      ...attributes,
      industries: attributes.industries.filter((_, i) => i !== index)
    })
  }

  const handleAddJobTitle = () => {
    if (!newJobTitle.trim() || !attributes) return
    setAttributes({
      ...attributes,
      jobTitles: [...attributes.jobTitles, newJobTitle.trim()]
    })
    setNewJobTitle("")
  }

  const handleRemoveJobTitle = (index: number) => {
    if (!attributes) return
    setAttributes({
      ...attributes,
      jobTitles: attributes.jobTitles.filter((_, i) => i !== index)
    })
  }

  const handleAddCompanySize = () => {
    if (!newCompanySize.trim() || !attributes) return
    setAttributes({
      ...attributes,
      companySizes: [...attributes.companySizes, newCompanySize.trim()]
    })
    setNewCompanySize("")
  }

  const handleRemoveCompanySize = (index: number) => {
    if (!attributes) return
    setAttributes({
      ...attributes,
      companySizes: attributes.companySizes.filter((_, i) => i !== index)
    })
  }

  const handleAddLocation = () => {
    if (!newLocation.trim() || !attributes) return
    setAttributes({
      ...attributes,
      locations: [...attributes.locations, newLocation.trim()]
    })
    setNewLocation("")
  }

  const handleRemoveLocation = (index: number) => {
    if (!attributes) return
    setAttributes({
      ...attributes,
      locations: attributes.locations.filter((_, i) => i !== index)
    })
  }

  const handleSaveAndContinue = async () => {
    if (!attributes) return
    
    setSaving(true)
    
    // Simulate save
    await new Promise(resolve => setTimeout(resolve, 1000))
    
    // Save to localStorage (mock database)
    localStorage.setItem("prospectAttributes", JSON.stringify(attributes))
    
    setSaving(false)
    router.push("/dashboard/prospects/search")
  }

  const handleRegenerate = async () => {
    if (!attributes) return
    
    setLoading(true)
    // Simulate AI regeneration
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    const storedSetup = localStorage.getItem("productSetup")
    const productName = storedSetup ? JSON.parse(storedSetup).name : "Product"
    const description = storedSetup ? JSON.parse(storedSetup).description : ""
    
    const newAttributes = generateMockAttributes(productName, description)
    setAttributes(newAttributes)
    setLoading(false)
  }

  if (loading) {
    return (
      <div className="p-8 flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <Loader2 className="w-8 h-8 animate-spin mx-auto mb-4 text-blue-500" />
          <p className="text-gray-500">Loading attributes...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">Prospect Attributes</h1>
        <p className="text-gray-500 mt-1">
          Review and edit the AI-generated attributes for your ideal prospects
        </p>
      </div>

      {attributes && (
        <div className="space-y-6">
          {/* Industries */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Building className="w-5 h-5" />
                Industries
              </CardTitle>
              <CardDescription>
                Target industries for your prospects
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2 mb-4">
                {attributes.industries.map((industry, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm"
                  >
                    {industry}
                    <button
                      onClick={() => handleRemoveIndustry(index)}
                      className="hover:text-blue-600"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </span>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  placeholder="Add new industry"
                  value={newIndustry}
                  onChange={(e) => setNewIndustry(e.target.value)}
                  onKeyPress={(e) => e.key === "Enter" && handleAddIndustry()}
                />
                <Button onClick={handleAddIndustry} variant="outline">
                  <Plus className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Job Titles */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Briefcase className="w-5 h-5" />
                Job Titles
              </CardTitle>
              <CardDescription>
                Target job titles/roles
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2 mb-4">
                {attributes.jobTitles.map((title, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-green-100 text-green-800 rounded-full text-sm"
                  >
                    {title}
                    <button
                      onClick={() => handleRemoveJobTitle(index)}
                      className="hover:text-green-600"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </span>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  placeholder="Add new job title"
                  value={newJobTitle}
                  onChange={(e) => setNewJobTitle(e.target.value)}
                  onKeyPress={(e) => e.key === "Enter" && handleAddJobTitle()}
                />
                <Button onClick={handleAddJobTitle} variant="outline">
                  <Plus className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Company Sizes */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Building className="w-5 h-5" />
                Company Sizes
              </CardTitle>
              <CardDescription>
                Target company sizes
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2 mb-4">
                {attributes.companySizes.map((size, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-purple-100 text-purple-800 rounded-full text-sm"
                  >
                    {size}
                    <button
                      onClick={() => handleRemoveCompanySize(index)}
                      className="hover:text-purple-600"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </span>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  placeholder="Add company size (e.g., 51-200 employees)"
                  value={newCompanySize}
                  onChange={(e) => setNewCompanySize(e.target.value)}
                  onKeyPress={(e) => e.key === "Enter" && handleAddCompanySize()}
                />
                <Button onClick={handleAddCompanySize} variant="outline">
                  <Plus className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Locations */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <MapPin className="w-5 h-5" />
                Locations
              </CardTitle>
              <CardDescription>
                Target geographic locations
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2 mb-4">
                {attributes.locations.map((location, index) => (
                  <span
                    key={index}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-orange-100 text-orange-800 rounded-full text-sm"
                  >
                    {location}
                    <button
                      onClick={() => handleRemoveLocation(index)}
                      className="hover:text-orange-600"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </span>
                ))}
              </div>
              <div className="flex gap-2">
                <Input
                  placeholder="Add new location"
                  value={newLocation}
                  onChange={(e) => setNewLocation(e.target.value)}
                  onKeyPress={(e) => e.key === "Enter" && handleAddLocation()}
                />
                <Button onClick={handleAddLocation} variant="outline">
                  <Plus className="w-4 h-4" />
                </Button>
              </div>
            </CardContent>
          </Card>

          {/* Actions */}
          <div className="flex justify-between pt-4">
            <Button 
              variant="outline" 
              onClick={() => router.push("/dashboard/prospects/setup")}
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Setup
            </Button>
            
            <div className="flex gap-2">
              <Button 
                variant="outline" 
                onClick={handleRegenerate}
                disabled={loading}
              >
                <Sparkles className="w-4 h-4 mr-2" />
                Regenerate with AI
              </Button>
              <Button 
                onClick={handleSaveAndContinue}
                disabled={saving}
              >
                {saving ? (
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                ) : (
                  <>
                    Save & Continue
                    <ArrowRight className="w-4 h-4 ml-2" />
                  </>
                )}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
